config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items do
    member do
      patch :complete
    end
  end
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user

    def completed
        !completed_at.blank?
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :items
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    before_action :item_find , only: [:show,:update,:edit,:destroy]
    before_action :authenticate_user! , except: [:index]

    def index
        if user_signed_in?
            @items=Item.where(user_id: current_user.id).order("created_at DESC")
        end
    end

    def new
        @item=current_user.items.build
    end

    def show
    end

    def edit
    end

    def update
        if @item.update(item_params)
            redirect_to item_path(@item)
        else
            render edit_item_path(@item) 
        end
    end

    def destroy
        @item.destroy
        redirect_to root_path
    end

    def create
        @item=current_user.items.build(item_params)
        if @item.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def complete
        @item=Item.find(params[:id])
        @item.update_attribute(:completed_at,Time.now)
        redirect_to root_path , notice: "The item is completed successfully"
    end

    private
     def item_params
        params.require(:item).permit(:title,:description)
     end

     def item_find
        @item=Item.find(params[:id])
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
    <%= f.input :title, label: "item" %>
    <%= f.input :description %>
    <%= f.button :submit ,class: "btn btn-primary"%>

<% end %>

app/views/items/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Edit Item</div>
  <div class="panel-body">
        <%= render 'form' %>
  </div>
</div>
<%= link_to  root_path ,class: "btn btn-primary" do %>
     <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"> Back</span>
<% end %>

app/views/items/index.html.erb
<% if user_signed_in? %>
<div class="col-md-6 col-md-offset-3">

    <% @items.each do |item| %>
    <div class="row item">
        <% if item.completed %>
        
        <div class="col-md-6">
                <h2 style="opacity: 0,5"><strike><%= link_to item.title , item_path(item) %></strike></h2>
            <p>
                <%= item.description %>
            </p>
            <span>
            Completed in <%= time_ago_in_words(item.completed_at) %>
            </span>
        </div>
        <div class="col-md-2">
        <%= link_to  complete_item_path(item) ,method: :patch,class: "btn btn-success" do %>
                Completed <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
            <% end %>
        </div>
        <div class="col-md-2 col-md-offset-2">
            <%= link_to  item_path(item) ,method: :delete ,data:{confirm: "Are you sure"} ,class: "btn btn-danger" do %>
                Delete <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            <% end %>
        </div>

        <% else %>
        <div class="col-md-6">
        <h2><%= link_to item.title , item_path(item) %></h2>
            <p>
                <%= item.description %>
            </p>
        </div>
        <div class="col-md-2">
            <%= link_to  complete_item_path(item) ,method: :patch,class: "btn btn-success" do %>
                Completed <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
            <% end %>
        </div>
        <div class="col-md-2 col-md-offset-2">
            <%= link_to  item_path(item) ,method: :delete ,data:{confirm: "Are you sure"} ,class: "btn btn-danger" do %>
                Delete <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            <% end %>
        </div>
        
        
        <% end %>
        </div>
    <% end %>
</div>

<% else %>
  <%= render 'layouts/static_land_page' %>
<% end %>

app/views/items/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">New Item</div>
  <div class="panel-body">
        <%= render 'form' %>
  </div>
</div>
<%= link_to  root_path ,class: "btn btn-primary" do %>
     <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"> Back</span>
<% end %>

app/views/items/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Details of Item </div>
  <div class="panel-body">
    <h2>
        <%= @item.title %>
    </h2>
    <p>
        <%= @item.description %>
    </p>
    <%= link_to  edit_item_path(@item) ,class: "btn btn-warning " do %>
         <span class="glyphicon glyphicon-pencil" aria-hidden="true"> Edit</span>
    <% end %>
    <%= link_to  item_path(@item),method: :delete, data: {confirm: "are you sure"} ,class:"btn btn-danger" do %>
          <span class="glyphicon glyphicon-trash" aria-hidden="true"> Delete</span>
    <% end %>
  </div>
</div>


<%= link_to  root_path ,class: "btn btn-primary" do %>
     <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"> Back</span>
<% end %>

app/views/layouts/_static_land_page.html.erb
<div class="jumbotron">
  <h1 class="display-4">Welcome to your checklist</h1>
  <p class="lead">Keep track your todo list</p>
  <hr class="my-4">
  <p>add your items and check your list and organize your priority</p>
  <p class="lead">
  
    <%= link_to 'Sign Up', new_user_registration_path , class: "btn btn-primary btn-lg" %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyChecklist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <%= link_to 'MyChecklist', root_path ,class:"navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse ">
          <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to 'New Item', new_item_path %></li>
         
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          
          <% if current_user.present? %>
            <li><%=link_to 'Sign Out', destroy_user_session_path,method: :delete %></li>
          <% else %>
            <li>
            <%=link_to  new_user_registration_path  do %>
              <span class="glyphicon glyphicon-plus-sign" aria-hidden="true">SignUp</span>
              <% end %>
            </li>
            <li> 
            <%= link_to  new_user_session_path  do %> 
             <span class="glyphicon glyphicon-log-in" aria-hidden="true"> Login</span>
            <% end %>
            </li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  
  </body>
</html>